### ISSUE TITLE
Need a UI list component

### ISSUE THREAD

**Issue by rbrtsmith** [rbrtsmith/nebula-components#23]
* Just a stacked list with borders between the list items

**Comment by kwood15** [comment]
Please review: Story - #23

Screenshots here:

![screen shot 2017-09-15 at 13 55 11](https://user-images.githubusercontent.com/11405108/30483241-150a904a-9a1e-11e7-95ef-4ecd415f1163.png)

![screen shot 2017-09-15 at 13 55 25](https://user-images.githubusercontent.com/11405108/30483244-1d13ec00-9a1e-11e7-8627-6e46892be272.png)
