### ISSUE TITLE
Allow for insertion of Icons on status cards

### ISSUE THREAD

**Issue by rbrtsmith** [rbrtsmith/nebula-components#40]
See #39

**Comment by kwood15** [comment]
Have done this now. I have refactored the status cards to allow for icons and have given an example of this below - no icon work included in this pr as I will work on the toast in a different branch - just showing you that they will work. Screenshots here:

![screen shot 2017-09-25 at 17 12 19](https://user-images.githubusercontent.com/11405108/30820119-e2585a76-a218-11e7-9987-c15d1ca57389.png)

![screen shot 2017-09-25 at 17 12 44](https://user-images.githubusercontent.com/11405108/30820120-e25a0b14-a218-11e7-9fba-31cbe69a9940.png)

![screen shot 2017-09-25 at 17 31 58](https://user-images.githubusercontent.com/11405108/30820147-f757838e-a218-11e7-80a0-728142550c49.png)

![screen shot 2017-09-25 at 17 36 46](https://user-images.githubusercontent.com/11405108/30820161-005d619c-a219-11e7-999d-b84cf32ca7c8.png)
